name: Upload/Publish MPAK

on:
  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout F7FeatherDemo
      uses: actions/checkout@v3
      with:
        path: F7FeatherDemo

    - name: Build + Upload
      uses: WildernessLabs/meadow-cloud-package-upload
      with:
        project_path: "F7FeatherDemo/Source/F7FeatherDemo"
        organization_id: ${{ secrets.CONFIG_ORGANIZATION_ID }} # set this to your organization
        api_key: ${{ secrets.API_KEY }} # set this to an api key that has package scope        
        os_version: "1.12.0.0" # Optional, set this to the OS version if required        
        configs : '{"CONFIG_WIFI_SSID": "${{ secrets.CONFIG_WIFI_SSID }}", "CONFIG_WIFI_PASS": "${{ secrets.CONFIG_WIFI_PASS }}"}' # Optional, set this to a matching token to replaced within your *.yaml files if required
    
    - name: Publish
      uses: WildernessLabs/meadow-cloud-package-publish
      with:        
        api_key: ${{ secrets.API_KEY }} # set this to an api key that has package scope        
        collection_id: ${{ secrets.CONFIG_COLLECTIONS_ID }} # set this to an api key that has package scope        
        metadata: "metadata part of my publish" # Optional, set this to the desired metadata for publish if required
